server:
    port: 9000
spring:
    data.mongodb.host: localhost
    data.mongodb.port: 27017
    data.mongodb.database: personDb
---
spring:
    profiles: development
    data.mongodb.host: localhost
    data.mongodb.port: 27017
    data.mongodb.database: personDb
    thymeleaf.cache: false
server:
    port: 9001
---
spring:
    profiles: production
    data.mongodb.host: localhost
    data.mongodb.port: 27017
    data.mongodb.database: person_testdb
    data.mongodb.username: testuser
    data.mongodb.password: testpassword123
server:
    port: 9001